id: IB43B81C5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:18:00+00:00'
last_modified: '2022-06-08T03:30:03.009468+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17033
  title: ཀླུ་བཙན་ཞགས་གྲོལ་དང་བརྒྱ་བཞིའི་ཆོ་ག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    71F2:
      image_group_id: I8LS17036
      title: ''
      total_pages: 300
      order: 1
      base_file: 71F2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
