id: P005496
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:54:39.572524
source_metadata:
  id: bdr:W8LS17033
  title: ཀླུ་བཙན་ཞགས་གྲོལ་དང་བརྒྱ་བཞིའི་ཆོ་ག
  author: ''
  volumes:
    2fc66a848d6f40cbb60b4904eb61110d:
      image_group_id: I8LS17036
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
